version: '3.8'
services:
  core_service:
    build:
      context: ./core_service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - COINMARKETCAP_API_KEY=${COINMARKETCAP_API_KEY}
    depends_on:
      - postgres
      - redis
    networks:
      - austeris-network
    restart: unless-stopped

  postgres:
    image: postgres:15
    platform: linux/arm64
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=austeris
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - austeris-network
    restart: unless-stopped

  redis:
    image: redis:7
    platform: linux/arm64
    volumes:
      - redis_data:/data
    networks:
      - austeris-network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    platform: linux/arm64
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - austeris-network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  austeris-network:
    driver: bridge