CREATE TABLE assets (
    id SERIAL PRIMARY KEY,
    symbol VARCHAR(10) NOT NULL,
    name VARCHAR(50) NOT NULL,
    cmc_id VARCHAR(50) UNIQUE NOT NULL,
    decimals INT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);